export enum AgentType {
  COMPANY_PROFILE_DB = 'COMPANY_PROFILE_DB',
  COMPANY_RESEARCH_OVERVIEW = 'COMPANY_RESEARCH_OVERVIEW',

  THREE_WHYS_MEDDPIC = 'THREE_WHYS_MEDDPIC',
  PARTNER_COMPETITOR = 'PARTNER_COMPETITOR',
  SCORING = 'SCORING',
  CONTACT_ENRICHMENT = 'CONTACT_ENRICHMENT',
}
