export enum PipelineStatus {
  QUEUED = 'QUEUED',
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
  PARTIAL_SUCCEEDED = 'PARTIAL_SUCCEEDED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
