export enum ResearchTool {
  ALL = 'ALL',

  THREE_WHYS_MEDDPIC = 'THREE_WHYS_MEDDPIC',
  PARTNER_COMPETITOR = 'PARTNER_COMPETITOR',
  SCORING = 'SCORING',
  CONTACT_ENRICHMENT = 'CONTACT_ENRICHMENT',
}
